### ISSUE TITLE
How to generate device properties from a device?

### ISSUE THREAD

**Issue by Bnaya** [yeriomin/play-store-api#26]
First i want to thank you for that amazing project!
Is there a script that can create device properties from a device? (using adb or so)
Or, what are the values i need to read from the device for each entry?
Thanks!

**Comment by Bnaya** [comment]
I've managed to get the properties file from /data/data/com.github.yeriomin.yalpstore/cache/device-vbox86p.properties
After installing and running the yeriomin/YalpStore app
Thanks!

**Comment by yeriomin** [comment]
I'm glad you find my project useful.

There are thousands of device definitions here: https://github.com/yeriomin/play-store-api/tree/alldevices/src/main/resources

Also, here is the class which builds device definition files in Yalp Store: https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/bugreport/BugReportDeviceInfoBuilder.java

**Comment by dyeray** [comment]
Hi!

Sorry for resurrecting this issue. I'd love to have some Moto info available for spoofing on Yalp store. I've got access to a Moto G5 and Moto E3. I've checked the directory data/com.github.yeriomin.yalpstore/ but I don't see any chache directory? Are there any instructions on how to generate them and if I got some device definitions, would you be interested on adding them to Yalp Store?

Regards.

**Comment by yeriomin** [comment]
@dyeray 
Hello.

>I'd love to have some Moto info available for spoofing on Yalp store.

I'm pretty sure you can find them following the link in my previous comment. Definitions have the device's codename in their name.

Device definitions are generated when you send a bug report. Since I don't see why would anyone want their own device definition, I never made any user accessible way to do it. But if you really want them for some reason, you can tap on the developer's email on the About page inside Yalp Store. This will generate the definition and send me a letter with it. After that you can take the definition from the sent letter. I know, not user-friendly at all.

/data/data/com.github.yeriomin.yalpstore/cache/ is a temporary files directory. Due to its nature you are not guaranteed to find anything there, it is not there to store things. @Bnaya was just lucky. But it might be there immediately after sending the bug report.

>would you be interested on adding them to Yalp Store?

No, adding any more will make Yalp Store apk a lot bigger. Sorry. And there are plenty of contemporary devices which are quite close (from the hardware point of view) to your Motos there, Google Pixels for example.

**Comment by dyeray** [comment]
Hi @yeriomin thanks for the reply! Sorry, I think I need to clarify it a bit more. My phone is not a Motorola (it's actually a Xiaomi), but I want to spoof a Motorola to be able to install apps developed by Motorola. I just pointed out that I can get access to some moto devices if that is needed to get a Motorola on the spoof list.

Regards!

**Comment by jmichael2497** [comment]
if you can't think of any use cases for people wanting to save their own specific device properties vs getting something from the "close enough" collection that needs corrections for region, etc, then here are a few:

* gdpr because v45 prompts users to send in their own device info as soon as they try to use the spoof system... it seems like it would be appropriate to put that in an accessible location for user use as well.

* checking to see exactly what will be available for one's own various model devices as can be done in the google play store to see what is compatible with your other devices...

* evaluating upgrade benefits vs downgrade to restore functions under various stock vs community builds for example Stock J vs CM K, or maybe Stock M vs LOS N/O/P.

* going into an area with poor internet availability and wanting to load up on compatible updates for those folks cheap intended disposable trash devices.

meanwhile as a workaround, ended up using the very roundabout email method and "share via http" download to get my own profiles from a few devices.
